[profile.default]
solc_version = "0.8.25"
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 1_000
bytecode_hash = "none"
fs_permissions = [{ access = "read-write", path = "./deployments/"}]

[rpc_endpoints]
base = "https://mainnet.base.org"
base_sepolia = "https://sepolia.base.org"

[etherscan]
base = { key = "${ETHERSCAN_BASE_KEY}" }
base_sepolia = { key = "${ETHERSCAN_BASE_KEY}" }

[fmt]
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
